server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hippus
#    username: postgres
    url: jdbc:mysql://localhost:3306/hippus?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&allowPublicKeyRetrieval=TRUE
    username: root
    password: xm12345678
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 200s
        max-idle: 8
        min-idle: 8
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml